version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "80:80"
